"""
app.py
AI YouTube Script Generator - Streamlit Web UI
Author: Muhammad Umar Malik
GitHub: https://github.com/Umar-Software-House

Run with:  streamlit run app.py
"""

import os
from datetime import datetime
import streamlit as st
from dotenv import load_dotenv
from openai import OpenAI

from script_generator import generate_script
from title_generator import generate_titles, generate_description
from hashtag_generator import generate_hashtags

# ── Page configuration ─────────────────────────────────────────────────────────
st.set_page_config(
    page_title="AI YouTube Script Generator",
    page_icon="🎬",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Load environment variables ─────────────────────────────────────────────────
load_dotenv()


# ── Custom CSS ─────────────────────────────────────────────────────────────────
st.markdown(
    """
    <style>
        .main-title {
            font-size: 2.5rem;
            font-weight: 800;
            color: #FF0000;
            text-align: center;
            margin-bottom: 0.2rem;
        }
        .subtitle {
            font-size: 1.1rem;
            color: #888;
            text-align: center;
            margin-bottom: 2rem;
        }
        .result-box {
            background-color: #1e1e2e;
            border-radius: 10px;
            padding: 1.2rem;
            border-left: 4px solid #FF0000;
            color: #cdd6f4;
            font-size: 0.95rem;
            line-height: 1.7;
            white-space: pre-wrap;
        }
        .section-header {
            font-size: 1.2rem;
            font-weight: 700;
            margin-top: 1.5rem;
            margin-bottom: 0.5rem;
        }
        .footer {
            text-align: center;
            color: #888;
            margin-top: 3rem;
            font-size: 0.85rem;
        }
    </style>
    """,
    unsafe_allow_html=True,
)


def get_openai_client(api_key: str) -> OpenAI:
    """Return an authenticated OpenAI client using the provided key."""
    return OpenAI(api_key=api_key)


def build_download_content(
    topic: str, titles: str, description: str, hashtags: str, script: str
) -> str:
    """Build the full plain-text content for the download file."""
    return f"""AI YouTube Script Generator
Generated on: {datetime.now().strftime("%B %d, %Y at %I:%M %p")}
Topic: {topic}
{'=' * 64}

📌 YOUTUBE TITLES
{'-' * 64}
{titles}

📋 VIDEO DESCRIPTION
{'-' * 64}
{description}

🏷️  HASHTAGS
{'-' * 64}
{hashtags}

🎬 FULL YOUTUBE SCRIPT
{'-' * 64}
{script}

{'=' * 64}
Generated by AI YouTube Script Generator
Author: Muhammad Umar Malik | github.com/Umar-Software-House
"""


# ── Sidebar ────────────────────────────────────────────────────────────────────
with st.sidebar:
    st.image(
        "https://img.icons8.com/color/96/youtube-play.png",
        width=80,
    )
    st.markdown("### ⚙️ Configuration")
    st.markdown("---")

    # API key input — prefer env variable, allow manual override
    env_key = os.getenv("OPENAI_API_KEY", "")
    api_key_input = st.text_input(
        "OpenAI API Key",
        value=env_key,
        type="password",
        help="Your secret key from platform.openai.com/api-keys",
        placeholder="sk-xxxxxxxxxxxxxxxx",
    )

    st.markdown("---")
    st.markdown("**How to get an API key:**")
    st.markdown("1. Go to [platform.openai.com](https://platform.openai.com)")
    st.markdown("2. Sign in / Sign up")
    st.markdown("3. Navigate to **API Keys**")
    st.markdown("4. Click **Create new secret key**")
    st.markdown("---")
    st.markdown(
        "Built by **Muhammad Umar Malik**  \n"
        "[GitHub](https://github.com/Umar-Software-House) · "
        "[Portfolio](https://muhammadumarmalik.me)"
    )


# ── Main UI ────────────────────────────────────────────────────────────────────
st.markdown('<div class="main-title">🎬 AI YouTube Script Generator</div>', unsafe_allow_html=True)
st.markdown(
    '<div class="subtitle">Generate Scripts · Titles · Descriptions · Hashtags with AI</div>',
    unsafe_allow_html=True,
)

st.markdown("---")

topic = st.text_input(
    "Enter your video topic",
    placeholder='e.g. "Apple vs Samsung rivalry history"',
    help="Be as specific or broad as you like. The more detail, the better the result.",
)

generate_btn = st.button("🚀 Generate Content", type="primary", use_container_width=True)

# ── Generation logic ───────────────────────────────────────────────────────────
if generate_btn:
    if not api_key_input:
        st.error("❌ Please enter your OpenAI API key in the sidebar before generating.")
        st.stop()

    if not topic.strip():
        st.warning("⚠️ Please enter a topic before clicking Generate.")
        st.stop()

    client = get_openai_client(api_key_input)

    with st.spinner("Generating your content — this usually takes 20-40 seconds..."):
        progress = st.progress(0, text="Starting...")

        try:
            progress.progress(10, text="🔄 Generating YouTube titles...")
            titles = generate_titles(topic, client)

            progress.progress(35, text="🔄 Generating video description...")
            description = generate_description(topic, client)

            progress.progress(60, text="🔄 Generating hashtags...")
            hashtags = generate_hashtags(topic, client)

            progress.progress(75, text="🔄 Generating full YouTube script (longest step)...")
            script = generate_script(topic, client)

            progress.progress(100, text="✅ Done!")

        except Exception as e:
            st.error(f"❌ An error occurred: {e}")
            st.info(
                "Common causes:\n"
                "- Invalid or expired API key\n"
                "- Insufficient OpenAI credits\n"
                "- Network connection issue"
            )
            st.stop()

    st.success("✅ All content generated successfully!")

    # ── Display results in tabs ────────────────────────────────────────────────
    tab1, tab2, tab3, tab4 = st.tabs(
        ["📌 Titles", "📋 Description", "🏷️ Hashtags", "🎬 Full Script"]
    )

    with tab1:
        st.markdown("### 📌 YouTube Title Ideas")
        st.markdown(
            f'<div class="result-box">{titles}</div>',
            unsafe_allow_html=True,
        )
        st.button("📋 Copy Titles", key="copy_titles", help="Select text above to copy")

    with tab2:
        st.markdown("### 📋 Video Description")
        st.markdown(
            f'<div class="result-box">{description}</div>',
            unsafe_allow_html=True,
        )

    with tab3:
        st.markdown("### 🏷️ Hashtags")
        st.markdown(
            f'<div class="result-box">{hashtags}</div>',
            unsafe_allow_html=True,
        )

    with tab4:
        st.markdown("### 🎬 Full YouTube Script")
        st.markdown(
            f'<div class="result-box">{script}</div>',
            unsafe_allow_html=True,
        )

    # ── Download button ────────────────────────────────────────────────────────
    st.markdown("---")
    download_content = build_download_content(topic, titles, description, hashtags, script)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    st.download_button(
        label="💾 Download All Results as .txt",
        data=download_content,
        file_name=f"output_script_{timestamp}.txt",
        mime="text/plain",
        use_container_width=True,
    )

# ── Footer ─────────────────────────────────────────────────────────────────────
st.markdown(
    '<div class="footer">AI YouTube Script Generator · Built by Muhammad Umar Malik · '
    '<a href="https://github.com/Umar-Software-House" target="_blank">GitHub</a> · '
    '<a href="https://muhammadumarmalik.me" target="_blank">Portfolio</a></div>',
    unsafe_allow_html=True,
)
