"""
main.py
AI YouTube Script Generator - Command Line Interface
Author: Muhammad Umar Malik
GitHub: https://github.com/Umar-Software-House
"""

import os
import sys
from datetime import datetime
from dotenv import load_dotenv
from groq import Groq

from script_generator import generate_script
from title_generator import generate_titles, generate_description
from hashtag_generator import generate_hashtags

# ── Load environment variables from .env file ──────────────────────────────────
load_dotenv()


def get_groq_client() -> Groq:
    """
    Initialise and return an authenticated Groq client.
    Exits with a helpful error message if the API key is missing.
    """
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        print("\n❌  ERROR: GROQ_API_KEY not found.")
        print("   Please copy .env.example to .env and add your Groq API key.")
        print("   Get a FREE key at: https://console.groq.com/keys\n")
        sys.exit(1)
    return Groq(api_key=api_key)


def print_banner() -> None:
    """Print a styled welcome banner to the terminal."""
    banner = """
╔══════════════════════════════════════════════════════════════╗
║          🎬  AI YouTube Script Generator  🎬                 ║
║                                                              ║
║   Generate Scripts · Titles · Descriptions · Hashtags       ║
║   Powered by Groq (Free)  |  Built by Muhammad Umar Malik    ║
╚══════════════════════════════════════════════════════════════╝
"""
    print(banner)


def print_section(title: str, content: str) -> None:
    """Print a formatted section with a title and content."""
    separator = "─" * 64
    print(f"\n{separator}")
    print(f"  {title}")
    print(separator)
    print(content)


def save_output(topic: str, titles: str, description: str, hashtags: str, script: str) -> str:
    """
    Save all generated content to a timestamped text file.

    Args:
        topic:       The original topic entered by the user.
        titles:      Generated YouTube titles.
        description: Generated video description.
        hashtags:    Generated hashtags.
        script:      Generated YouTube script.

    Returns:
        The file path of the saved output file.
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"output_script_{timestamp}.txt"

    content = f"""AI YouTube Script Generator
Generated on: {datetime.now().strftime("%B %d, %Y at %I:%M %p")}
Topic: {topic}
{'=' * 64}

📌 YOUTUBE TITLES
{'-' * 64}
{titles}

📋 VIDEO DESCRIPTION
{'-' * 64}
{description}

🏷️  HASHTAGS
{'-' * 64}
{hashtags}

🎬 FULL YOUTUBE SCRIPT
{'-' * 64}
{script}

{'=' * 64}
Generated by AI YouTube Script Generator
Author: Muhammad Umar Malik | github.com/Umar-Software-House
"""

    with open(filename, "w", encoding="utf-8") as f:
        f.write(content)

    return filename


def main() -> None:
    """Main entry point for the CLI application."""
    print_banner()

    # ── Get topic from user ────────────────────────────────────────────────────
    print("Enter the topic for your YouTube video.")
    print('Example: "Apple vs Samsung rivalry history"\n')
    topic = input("📝  Your topic: ").strip()

    if not topic:
        print("\n❌  No topic entered. Please run the script again and enter a topic.\n")
        sys.exit(1)

    print(f'\n✅  Topic received: "{topic}"')
    print("\n⏳  Connecting to OpenAI and generating your content...")
    print("    (This may take 20-40 seconds depending on your connection)\n")

    # ── Initialise Groq client ─────────────────────────────────────────────────
    client = get_groq_client()

    # ── Generate all content ───────────────────────────────────────────────────
    print("🔄  [1/4] Generating YouTube titles...")
    titles = generate_titles(topic, client)

    print("🔄  [2/4] Generating video description...")
    description = generate_description(topic, client)

    print("🔄  [3/4] Generating hashtags...")
    hashtags = generate_hashtags(topic, client)

    print("🔄  [4/4] Generating full YouTube script (this is the longest step)...")
    script = generate_script(topic, client)

    print("\n✅  All content generated successfully!\n")

    # ── Display results ────────────────────────────────────────────────────────
    print_section("📌  YOUTUBE TITLES", titles)
    print_section("📋  VIDEO DESCRIPTION", description)
    print_section("🏷️   HASHTAGS", hashtags)
    print_section("🎬  FULL YOUTUBE SCRIPT", script)

    # ── Save to file ───────────────────────────────────────────────────────────
    output_file = save_output(topic, titles, description, hashtags, script)

    print(f"\n{'═' * 64}")
    print(f"  💾  Output saved to: {output_file}")
    print(f"{'═' * 64}\n")
    print("Thank you for using AI YouTube Script Generator!")
    print("Built by Muhammad Umar Malik | github.com/Umar-Software-House\n")


if __name__ == "__main__":
    main()
